export type PlaceholderProduct = {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  priceCents: number;
  compareAtPriceCents?: number;
  category: { name: string; slug: string };
  caseSize: string;
  sku: string;
  imageUrl: string;
};

export const PLACEHOLDER_PRODUCTS: PlaceholderProduct[] = [
  {
    id: "ph-multigrain-crackers",
    slug: "sea-salt-multigrain-crackers",
    title: "Sea Salt Multigrain Crackers, 6.5 oz",
    shortDescription: "Crisp multigrain crackers with rolled oats and a light sea-salt finish.",
    priceCents: 449,
    category: { name: "Grocery & Snacks", slug: "grocery-snacks" },
    caseSize: "Case of 12",
    sku: "PRN-GRC-1001",
    imageUrl: "https://images.unsplash.com/photo-1599629954294-14df9ec8bc1c?w=1200&q=80",
  },
  {
    id: "ph-honey-roasted-almonds",
    slug: "honey-roasted-almonds",
    title: "Honey Roasted Almonds, 9 oz Resealable",
    shortDescription: "Whole almonds, lightly glazed with honey and a touch of cane sugar.",
    priceCents: 799,
    compareAtPriceCents: 899,
    category: { name: "Grocery & Snacks", slug: "grocery-snacks" },
    caseSize: "Case of 8",
    sku: "PRN-GRC-1002",
    imageUrl: "https://images.unsplash.com/photo-1606937295547-bc0f668293db?w=1200&q=80",
  },
  {
    id: "ph-organic-rolled-oats",
    slug: "organic-rolled-oats",
    title: "Organic Rolled Oats, 32 oz Canister",
    shortDescription: "USDA-organic whole-grain rolled oats for consistent breakfast sets.",
    priceCents: 549,
    category: { name: "Grocery & Snacks", slug: "grocery-snacks" },
    caseSize: "Case of 6",
    sku: "PRN-GRC-1003",
    imageUrl: "https://images.unsplash.com/photo-1614961233913-a5113a4a34ed?w=1200&q=80",
  },
  {
    id: "ph-shelf-stable-protein-bars",
    slug: "protein-bars-variety-pack",
    title: "Protein Bar Variety Pack, 12 Count",
    shortDescription: "Individually wrapped bars designed for grab-and-go endcaps and checkout.",
    priceCents: 1299,
    category: { name: "Grocery & Snacks", slug: "grocery-snacks" },
    caseSize: "Case of 12",
    sku: "PRN-GRC-1004",
    imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc5000?w=1200&q=80",
  },
  {
    id: "ph-daily-moisturizer",
    slug: "daily-hydrating-facial-moisturizer",
    title: "Daily Hydrating Facial Moisturizer, 1.7 fl oz",
    shortDescription: "Lightweight daily moisturizer with hyaluronic acid and niacinamide.",
    priceCents: 1299,
    category: { name: "Health & Beauty", slug: "health-beauty" },
    caseSize: "Case of 24",
    sku: "PRN-HBA-2001",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=1200&q=80",
  },
  {
    id: "ph-mineral-sunscreen",
    slug: "mineral-sunscreen-spf-50",
    title: "Broad-Spectrum Mineral Sunscreen SPF 50, 3.0 fl oz",
    shortDescription: "Zinc-oxide mineral sunscreen, water-resistant up to 80 minutes.",
    priceCents: 1499,
    category: { name: "Health & Beauty", slug: "health-beauty" },
    caseSize: "Case of 24",
    sku: "PRN-HBA-2002",
    imageUrl: "https://images.unsplash.com/photo-1556228852-80b6e5eeff06?w=1200&q=80",
  },
  {
    id: "ph-vitamin-c-serum",
    slug: "vitamin-c-serum",
    title: "Brightening Vitamin C Serum, 1.0 fl oz",
    shortDescription: "Daily brightening serum formulated with vitamin C and vitamin E.",
    priceCents: 1899,
    compareAtPriceCents: 2299,
    category: { name: "Health & Beauty", slug: "health-beauty" },
    caseSize: "Case of 12",
    sku: "PRN-HBA-2003",
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=1200&q=80",
  },
  {
    id: "ph-free-clear-detergent",
    slug: "free-and-clear-laundry-detergent",
    title: "Free & Clear Liquid Laundry Detergent, 100 oz",
    shortDescription: "Dye- and fragrance-free detergent intended for high-turn laundry sets.",
    priceCents: 1399,
    category: { name: "Household Essentials", slug: "household-essentials" },
    caseSize: "Case of 4",
    sku: "PRN-HHE-3001",
    imageUrl: "https://images.unsplash.com/photo-1615840287214-7ff58936c4cf?w=1200&q=80",
  },
  {
    id: "ph-multi-surface-cleaner",
    slug: "citrus-multi-surface-cleaner",
    title: "Citrus Multi-Surface Cleaner, 32 fl oz",
    shortDescription: "Everyday cleaner with a fresh citrus profile for multiple surfaces.",
    priceCents: 549,
    category: { name: "Household Essentials", slug: "household-essentials" },
    caseSize: "Case of 12",
    sku: "PRN-HHE-3002",
    imageUrl: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=1200&q=80",
  },
  {
    id: "ph-premium-bath-tissue",
    slug: "premium-bath-tissue-12-mega-rolls",
    title: "2-Ply Premium Bath Tissue, 12 Mega Rolls",
    shortDescription: "Soft, strong, septic-safe bath tissue for value-driven paper aisles.",
    priceCents: 1899,
    category: { name: "Household Essentials", slug: "household-essentials" },
    caseSize: "Case of 4 packs",
    sku: "PRN-HHE-3003",
    imageUrl: "https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=1200&q=80",
  },
  {
    id: "ph-spring-water",
    slug: "natural-spring-water-24pk",
    title: "Natural Spring Water, 16.9 fl oz Bottles",
    shortDescription: "BPA-free bottled spring water designed for club and convenience sets.",
    priceCents: 599,
    category: { name: "Beverages", slug: "beverages" },
    caseSize: "Case of 24",
    sku: "PRN-BEV-4001",
    imageUrl: "https://images.unsplash.com/photo-1606168094336-48f8b0c1e1d2?w=1200&q=80",
  },
  {
    id: "ph-cold-brew-coffee",
    slug: "cold-brew-coffee-11oz",
    title: "Cold Brew Coffee, Unsweetened Black, 11 fl oz",
    shortDescription: "Single-serve cold brew in cans for refrigerated grab-and-go doors.",
    priceCents: 349,
    category: { name: "Beverages", slug: "beverages" },
    caseSize: "Case of 12",
    sku: "PRN-BEV-4002",
    imageUrl: "https://images.unsplash.com/photo-1559525839-d9acfd0b8ad7?w=1200&q=80",
  },
];
